notifications:
    email: false
os: linux
language : go
matrix:
    include:
      - language: node_js
        node_js: 
            - 10
        before_install:
            - cd frontend
  
      - language: go
        go:
            - 1.x
        before_install:
          - cd goBackend/backend && go generate
        script:
          - go build